<ul class="dropdown-menu">
	<li><a href="/">AX5UI</a></li>
	<li role="separator" class="divider"></li>
	<li><a href="/ax5core">ax5core</a></li>
	<li><a href="/bootstrap-ax5mask">bootstrap-ax5mask</a></li>
	<li><a href="/bootstrap-ax5dialog">bootstrap-ax5dialog</a></li>
	<li><a href="/bootstrap-ax5toast">bootstrap-ax5toast</a></li>
	<li><a href="/bootstrap-ax5modal">bootstrap-ax5modal</a></li>
	<li><a href="/bootstrap-ax5calendar">bootstrap-ax5calendar</a></li>
	<li><a href="/bootstrap-ax5picker">bootstrap-ax5picker</a></li>
	<li role="separator" class="divider"></li>
	<li><a href="https://www.axisj.com">axisj.com</a></li>
</ul>